### ISSUE TITLE
Question 9 of quiz is wrong

### ISSUE THREAD

**Issue by UltimateTrainer** [7-11-22-sdet-hooper/Database#6]
### Steps to reproduce
1.Go test.javalearninglab.com
2.Complete the quiz

### Expected result
White box testing is a test methodology that assumes explicit and substantial knowledge of the internal structure and implementation detail of the assessment object. Also known as white box testing.

### Actual result
The answer in the quiz section actual describes black box testing https://csrc.nist.gov/glossary/term/black_box_testing#:~:text=Also%20known%20as%20black%20box%20testing.&text=A%20method%20of%20software%20testing,%2C%20integration%2C%20system%20and%20acceptance.

### Visual proof
![chrome_VEXPsR28WO](https://user-images.githubusercontent.com/18106403/187926648-1207bb29-2998-41c1-bd7e-c04208860543.png)

### Reported by
Mitchell Nguyen

**Comment by DilanTanner** [comment]
Updated to show answer C as correct choice
